### ISSUE TITLE
MongoContainer and Tree component

### ISSUE THREAD

**Issue by ivan-osipov** [tyl/mongodbcontainer-addon#6]
We will need following to:
We have a mongo base with (for example) two collections: 
CollectionA:
  {name: "aaa" ...other params}
  {name: "bbb"}
CollectionB:
  {name: "qwerty"}
  {name: "ytrewq"}
We will need to create Tree component. We set for him mongo container and we get the follow result:

<b>Caption</b>
▼CollectionA
&nbsp;&nbsp;&nbsp;&nbsp;▼aaa
&nbsp;&nbsp;&nbsp;&nbsp;▼bbb
▼CollectionB
&nbsp;&nbsp;&nbsp;&nbsp;▼qwerty
&nbsp;&nbsp;&nbsp;&nbsp;▼ytrewq

In current time this released or not? and will you do this?

**Comment by evacchi** [comment]
Hi,

we have added support to Container.Hierarchical in v0.9.5.7-beta

The behavior is similar to that of JPAContainer; that is, in order to support hierarchical structures, your beans will have to define a `parent` property, that references the parent `ObjectId`. This follows a well-known pattern described in [MongoDB's documentation ("parent references")](http://docs.mongodb.org/manual/tutorial/model-tree-structures/#model-tree-structures-with-parent-references).

For a full usage example, see this gist:
https://gist.github.com/evacchi/3c4047ea2ca952bb07c3
