### ISSUE TITLE
Container does not fire ItemSetChange event when adding an entity

### ISSUE THREAD

**Issue by ares242** [tyl/mongodbcontainer-addon#8]
Hi,
I noticed this working with Vaadin grid, add an item to the container and the grid will not show the new item.

**Comment by evacchi** [comment]
definitely a bug; should be an easy fix too

**Comment by ares242** [comment]
It is the same for removing. In respect with value change events, grid add value change listeners to item properties but the container return a new bean in getItem(id), Would be possible not to get a new item in getItem(id) if that item is in the current page? or How would I fire value change events to make grid refresh a row?

**Comment by evacchi** [comment]
That is a different bug; it is the same bug I'm observing with [Viritin's ListContainer](https://github.com/viritin/viritin/issues/57#issuecomment-75030246); both containers (Mongo and List) are lazy, because they keep in memory as little as possible.

> Would be possible not to get a new item in getItem(id) if that item is in the current page?

Unfortunately this is something we tried, but it is not a solution. Assume that you enter "edit" mode in your Grid, then scroll, and cause MongoContainer to load a new page; then you get the same exact problem as the Item that is being edited won't be the same that is displayed anymore.

Currently, for Grid, I would advise using the BufferedMongoContainer, which includes the `updateItem(id)` method to make the `Item` corresponding to `id`  "stick" until you invoke either `commit()` or `discard()` on the Container.

**Comment by ares242** [comment]
Thanks man! add and remove works perfectly, that gist not make the grid updated when updating a item, would be usefull if this container fully supports grid features. I will try to find a solution around the gist.

**Comment by ares242** [comment]
This code force grid to refresh a given row, use it without the proxy.
```java
try {
        java.lang.reflect.Field f = grid.getClass().getDeclaredField("datasourceExtension");
        f.setAccessible(true);
        RpcDataProviderExtension rpc = (RpcDataProviderExtension) f.get(grid);
        rpc.updateRowData(obj.getId());
} catch (NoSuchFieldException e) {
        e.printStackTrace();
} catch (IllegalAccessException e) {
         e.printStackTrace();
}
```

**Comment by evacchi** [comment]
In fact I believe that should be actually public API in the Grid (see [https://vaadin.com/forum#!/thread/9319379](this forum thread)). I don't understand why it is not so (kinda love this act though :D)

**Comment by evacchi** [comment]
this relies on a side effect of the public API, but at least it's not using reflection:

            grid.setCellStyleGenerator(grid.getCellStyleGenerator());

**Comment by ares242** [comment]
The advantage of my aproach is that only updates the given row and no all the grid, despite being awkward.

**Comment by evacchi** [comment]
yep, I know. We'll just have to wait and see what upstream will do in this regard
